// Deploys GuardianVault + SimpleWallet to the running Hardhat node and
// writes the address + ABI into the frontend so the UI connects automatically.
//   npx hardhat node                                   (terminal 1)
//   npx hardhat run scripts/deploy.js --network localhost   (terminal 2)
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const { ethers, network } = hre;
  const [owner, g1, g2, g3, newOwner, attacker] = await ethers.getSigners();

  const Vault = await ethers.getContractFactory("GuardianVault");
  const vault = await Vault.deploy([g1.address, g2.address, g3.address]);
  await vault.waitForDeployment();
  const vaultReceipt = await vault.deploymentTransaction().wait();

  const Simple = await ethers.getContractFactory("SimpleWallet");
  const simple = await Simple.deploy();
  await simple.waitForDeployment();

  // The plain wallet is pre-funded to show "5 ETH locked forever" in the problem demo.
  await (await owner.sendTransaction({ to: await simple.getAddress(), value: ethers.parseEther("5") })).wait();

  const deployment = {
    network: network.name,
    chainId: Number((await ethers.provider.getNetwork()).chainId),
    guardianVault: await vault.getAddress(),
    simpleWallet: await simple.getAddress(),
    deployBlock: vaultReceipt.blockNumber,
    roles: {
      owner: owner.address,
      guardian1: g1.address,
      guardian2: g2.address,
      guardian3: g3.address,
      newOwner: newOwner.address,
      attacker: attacker.address,
    },
  };

  const feSrc = path.join(__dirname, "..", "frontend", "src");
  fs.mkdirSync(path.join(feSrc, "abi"), { recursive: true });
  fs.mkdirSync(path.join(feSrc, "utils"), { recursive: true });
  const abiOf = (name) =>
    JSON.parse(fs.readFileSync(path.join(__dirname, "..", "artifacts", "contracts", `${name}.sol`, `${name}.json`))).abi;
  fs.writeFileSync(path.join(feSrc, "abi", "GuardianVault.json"), JSON.stringify(abiOf("GuardianVault"), null, 2));
  fs.writeFileSync(path.join(feSrc, "abi", "SimpleWallet.json"), JSON.stringify(abiOf("SimpleWallet"), null, 2));
  fs.writeFileSync(
    path.join(feSrc, "utils", "contractAddress.js"),
    `// AUTO-GENERATED by scripts/deploy.js — do not edit by hand.\nexport const DEPLOYMENT = ${JSON.stringify(deployment, null, 2)};\n`
  );

  console.log("\nGuardianVault deployed:", deployment.guardianVault);
  console.log("SimpleWallet  deployed:", deployment.simpleWallet, "(pre-funded with 5 ETH)");
  console.log("\nRoles (Hardhat default accounts):");
  for (const [role, addr] of Object.entries(deployment.roles)) console.log(`  ${role.padEnd(10)} ${addr}`);
  console.log("\nFrontend config written to frontend/src/utils/contractAddress.js");
}

main().catch((e) => {
  console.error(e);
  process.exitCode = 1;
});
